FileVersion = 1
LastConfig = "Debug"
LastPlatform = "Win64"
RecentFilesList = ["src\\Game.bf", "src\\Util\\Debug.bf"]

[MainWindow]
X = 183
Y = 36
Width = 1169
Height = 877
ShowKind = "ShowNormal"

[MainDockingFrame]
Type = "DockingFrame"
SplitType = 2

[[MainDockingFrame.DockedWidgets]]
RequestedWidth = 350.0
RequestedHeight = 200.0
SizePriority = 200.0
Type = "DockingFrame"
SplitType = 1

[[MainDockingFrame.DockedWidgets.DockedWidgets]]
RequestedWidth = 274.0
RequestedHeight = 200.0
Type = "TabbedView"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
Active = true
TabLabel = "Workspace"
TabWidth = 113.2076
TabIsPinned = false
Type = "ProjectPanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets]]
IsFillWidget = true
Permanent = true
RequestedWidth = 1516.08
RequestedHeight = 370.8492
SizePriority = 1516.08
DefaultDocumentsTabbedView = true
Type = "TabbedView"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
Active = true
TabLabel = "Game.bf"
TabWidth = 87.73586
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "src\\Game.bf"
CursorPos = 251
ProjectName = "Rotworks-Game"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Debug.bf"
TabWidth = 82.83019
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "src\\Util\\Debug.bf"
CursorPos = 230
ProjectName = "Rotworks-Game"

[[MainDockingFrame.DockedWidgets]]
RequestedWidth = 250.0
RequestedHeight = 250.0
Type = "DockingFrame"
SplitType = 1

[[MainDockingFrame.DockedWidgets.DockedWidgets]]
RequestedWidth = 250.0
RequestedHeight = 250.0
SizePriority = 0.5
Type = "TabbedView"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
Active = true
TabLabel = "Output"
TabWidth = 92.45284
TabIsPinned = false
Type = "OutputPanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Errors"
TabWidth = 83.96227
TabIsPinned = false
Type = "ErrorsPanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Console"
TabWidth = 96.22642
TabIsPinned = false
Type = "ConsolePanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Diagnostics"
TabWidth = 116.0377
TabIsPinned = false
Type = "DiagnosticsPanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Memory"
TabWidth = 99.05661
TabIsPinned = false
Type = "MemoryPanel"
AutoResize = "Auto_Mul8"
RequestedWidth = 300.0

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Watch"
TabWidth = 86.79246
TabIsPinned = false
Type = "WatchPanel"
Columns = [{Width = 192.0}, {Width = 192.0}, {Width = 192.0}]

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs.Items]]
EvalStr = "Rotworks.Data.entities"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs.Items]]
EvalStr = ""

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Auto"
TabWidth = 78.30189
TabIsPinned = false
Type = "AutoWatchPanel"
Columns = [{Width = 192.0}, {Width = 192.0}, {Width = 192.0}]

[[MainDockingFrame.DockedWidgets.DockedWidgets]]
RequestedWidth = 250.0
RequestedHeight = 250.0
SizePriority = 0.5
Type = "TabbedView"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
Active = true
TabLabel = "Threads"
TabWidth = 95.28303
TabIsPinned = false
Type = "ThreadPanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Call Stack"
TabWidth = 104.717
TabIsPinned = false
Type = "CallStackPanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Immediate"
TabWidth = 111.3208
TabIsPinned = false
Type = "ImmediatePanel"

[[BookmarkFolders]]
Title = ""

[OutputFilters]
ModuleLoadMessages = false
ModuleUnloadMessages = false
ProcessExitMessages = false
ThreadCreateMessages = false
ThreadExitMessages = false
SymbolLoadMessages = false
ProgramOutput = false
