FileVersion = 1
Dependencies = {corlib = "*", raylib-beef = "*"}

[Project]
Name = "Rotworks-Game"
StartupObject = "Rotworks.Program"
DefaultNamespace = "Rotworks"

[Platform.Windows]
Description = "A fun little factory game"
Company = "The Doghouse"
Copyright = "Justin Macklin"
