FileVersion = 1
LastConfig = "Debug"
LastPlatform = "Win64"
RecentFilesList = ["Rotworks-Engine\\src\\Assets\\TextureManager.bf", "Rotworks-Engine\\src\\Entities\\Entity.bf", "Rotworks-Engine\\src\\SceneSystem\\SceneManager.bf"]

[MainWindow]
X = 183
Y = 155
Width = 1169
Height = 877
ShowKind = "ShowMaximized"

[MainDockingFrame]
Type = "DockingFrame"
SplitType = 2

[[MainDockingFrame.DockedWidgets]]
RequestedWidth = 350.0
RequestedHeight = 200.0
SizePriority = 200.0
Type = "DockingFrame"
SplitType = 1

[[MainDockingFrame.DockedWidgets.DockedWidgets]]
RequestedWidth = 274.0
RequestedHeight = 200.0
Type = "TabbedView"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
Active = true
TabLabel = "Workspace"
TabWidth = 116.3265
TabIsPinned = false
Type = "ProjectPanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets]]
IsFillWidget = true
Permanent = true
RequestedWidth = 1516.08
RequestedHeight = 370.8492
SizePriority = 1516.08
DefaultDocumentsTabbedView = true
Type = "TabbedView"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
Active = true
TabLabel = "TextureManager.bf"
TabWidth = 151.0204
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "Rotworks-Engine\\src\\Assets\\TextureManager.bf"
CursorPos = 71
ProjectName = "Rotworks-Engine"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Entity.bf"
TabWidth = 86.7347
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "Rotworks-Engine\\src\\Entities\\Entity.bf"
CursorPos = 197
ProjectName = "Rotworks-Engine"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "SceneManager.bf"
TabWidth = 142.8571
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "Rotworks-Engine\\src\\SceneSystem\\SceneManager.bf"
CursorPos = 341
ProjectName = "Rotworks-Engine"

[[MainDockingFrame.DockedWidgets]]
RequestedWidth = 250.0
RequestedHeight = 250.0
Type = "DockingFrame"
SplitType = 1

[[MainDockingFrame.DockedWidgets.DockedWidgets]]
RequestedWidth = 250.0
RequestedHeight = 250.0
SizePriority = 0.5
Type = "TabbedView"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
Active = true
TabLabel = "Output"
TabWidth = 90.81632
TabIsPinned = false
Type = "OutputPanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Errors"
TabWidth = 86.7347
TabIsPinned = false
Type = "ErrorsPanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Console"
TabWidth = 97.95918
TabIsPinned = false
Type = "ConsolePanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Diagnostics"
TabWidth = 118.3673
TabIsPinned = false
Type = "DiagnosticsPanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Memory"
TabWidth = 100.0
TabIsPinned = false
Type = "MemoryPanel"
AutoResize = "Auto_Mul8"
RequestedWidth = 300.0

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Watch"
TabWidth = 86.7347
TabIsPinned = false
Type = "WatchPanel"
Columns = [{Width = 192.0}, {Width = 192.0}, {Width = 192.0}]

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs.Items]]
EvalStr = "Rotworks.Data.entities"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs.Items]]
EvalStr = ""

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Auto"
TabWidth = 77.55102
TabIsPinned = false
Type = "AutoWatchPanel"
Columns = [{Width = 192.0}, {Width = 192.0}, {Width = 192.0}]

[[MainDockingFrame.DockedWidgets.DockedWidgets]]
RequestedWidth = 250.0
RequestedHeight = 250.0
SizePriority = 0.5
Type = "TabbedView"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
Active = true
TabLabel = "Threads"
TabWidth = 97.95918
TabIsPinned = false
Type = "ThreadPanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Call Stack"
TabWidth = 106.1224
TabIsPinned = false
Type = "CallStackPanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Immediate"
TabWidth = 112.2449
TabIsPinned = false
Type = "ImmediatePanel"

[[BookmarkFolders]]
Title = ""

[OutputFilters]
ModuleLoadMessages = false
ModuleUnloadMessages = false
ProcessExitMessages = false
ThreadCreateMessages = false
ThreadExitMessages = false
SymbolLoadMessages = false
ProgramOutput = false
